const int SEE_ALL_COLOR_TEXT = 0xffDD3F51;
const double SEE_ALL_SIZE = 14;
const double FONT_SIZE_BOLD_TITLE = 18;
const double FONT_SIZE_PAGE_TITLE = 28;
const double PAGE_TITLE_BOX_HEIGHT_RATIO = 0.132;
const double PAGE_TITLE_BOX_COMPACT_HEIGHT_RATIO = 0.075;