// SQUARE CARD CONST
const double SQUARE_CARD_HEIGHT_RATIO = 0.444;
const double SQUARE_CARD_WIDTH_RATIO = 0.292;
const int SQUARE_CARD_GREY = 0xff939393;
const double SQUARE_CARD_FONT_SIZE_TEXT = 13;
const double SQUARE_CARD_RADIUS = 5;
